# Generated by Django 2.0.3 on 2018-04-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
