# Generated by Django 2.0.3 on 2019-07-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20190716_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
