# Generated by Django 2.0.3 on 2019-07-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20190716_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['featured', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='link',
            name='votes',
        ),
    ]
