# Generated by Django 2.0.3 on 2019-07-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20190716_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
