# Generated by Django 2.0.3 on 2018-04-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
